### ISSUE TITLE
App crashes on some devices when installed on SD card

### ISSUE THREAD

**Issue by KimVinod** [KimVinod/bts-lyricz#7]
## Description
App crashes on some devices with ARM-32 bit when installed on SD card.

## Stacktrace
Crash caught by Firebase Crashlytics.

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kimvinod.bts_lyricz/com.kimvinod.bts_lyricz.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/mnt/asec/com.kimvinod.bts_lyricz-1/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libflutter.so" segment 2: Permission denied
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

## Possible Solution
Do not install the app on SD card.

#### Manufacturer:
Samsung
#### Android version: 
8.0

## Similar ongoing issue
[Google IssueTracker](https://issuetracker.google.com/issues/127691101)

**Comment by KimVinod** [comment]
Closed for now due to inactive
